In [2]:
import numpy as np
import pandas as pd
scores = np.random.randint(50,101,size=(50,5))
scores_pd = pd.DataFrame(scores,
             columns=['國文', '英文', '數學', '地理', '歷史'],
             index = range(1,51)
             )
scores_pd

     國文   英文   數學   地理   歷史
1    62   65   59  100   54
2    50   70  100   88   91
3    56   66   94   79   75
4    62   64   68   50   82
5    68   85   98   64   83
6    65   95   85   69   53
7    89  100   79   61   80
8    86   82   61   56   75
9    75   52   50   98   86
10   72   97   92   66   65
11   83   70   60   72   75
12   50   82   97   55   82
13   94   96   53   68   61
14   79   77  100   82   94
15   78   58   65   68   92
16   84   99   52   83   53
17   97   66   90   97   73
18   89   54   82   66   63
19   72   56   89   89   55
20  100   86   78   95   50
21   66   52   94   97  100
22   56   89   96   50   65
23   76   51   55   52   58
24   51   80   52   57   97
25   87   91   66   69   64
26   84   90   89   77   78
27   63   83   54   78   81
28   52   60   83   81   90
29   56   91   67   74   72
30   53   92   67   73   56
31   71   67   99   57   58
32   98   54   68   85   51
33   93   87   50   53   98
34   81   61   86   61   55
35   92  100   65   57   93
36   70   95   93   92  100
37   67   81   60   94   91
38   98  100   89   60   69
39   72  100   81   88   63
40   54   59   97   54   75
41   93   75   69   73   65
42   56   69   80   72   66
43   91   63   99   56   92
44   55   50   53   66   67
45   51   83   53   96   61
46   82   77   89   72   72
47   65   69  100  100   82
48   67   86   83   83   91
49   89   66   66   54   94
50   78   62   51   90   63

In [3]:
scores_pd.index.name="學號"
scores_pd.columns.name="科目"
scores_pd

科目   國文   英文   數學   地理   歷史
學號
1    62   65   59  100   54
2    50   70  100   88   91
3    56   66   94   79   75
4    62   64   68   50   82
5    68   85   98   64   83
6    65   95   85   69   53
7    89  100   79   61   80
8    86   82   61   56   75
9    75   52   50   98   86
10   72   97   92   66   65
11   83   70   60   72   75
12   50   82   97   55   82
13   94   96   53   68   61
14   79   77  100   82   94
15   78   58   65   68   92
16   84   99   52   83   53
17   97   66   90   97   73
18   89   54   82   66   63
19   72   56   89   89   55
20  100   86   78   95   50
21   66   52   94   97  100
22   56   89   96   50   65
23   76   51   55   52   58
24   51   80   52   57   97
25   87   91   66   69   64
26   84   90   89   77   78
27   63   83   54   78   81
28   52   60   83   81   90
29   56   91   67   74   72
30   53   92   67   73   56
31   71   67   99   57   58
32   98   54   68   85   51
33   93   87   50   53   98
34   81   61   86   61   55
35   92  100   65   57   93
36   70   95   93   92  100
37   67   81   60   94   91
38   98  100   89   60   69
39   72  100   81   88   63
40   54   59   97   54   75
41   93   75   69   73   65
42   56   69   80   72   66
43   91   63   99   56   92
44   55   50   53   66   67
45   51   83   53   96   61
46   82   77   89   72   72
47   65   69  100  100   82
48   67   86   83   83   91
49   89   66   66   54   94
50   78   62   51   90   63

In [4]:
display(scores_pd['國文'][:10])
scores_pd['數學'][:10]
scores_pd.info()

學號
1     62
2     50
3     56
4     62
5     68
6     65
7     89
8     86
9     75
10    72
Name: 國文, dtype: int32

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 1 to 50
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   國文      50 non-null     int32
 1   英文      50 non-null     int32
 2   數學      50 non-null     int32
 3   地理      50 non-null     int32
 4   歷史      50 non-null     int32
dtypes: int32(5)
memory usage: 1.1 KB

In [5]:
scores_pd['國文'][:10] + scores_pd['數學'][:10]

學號
1     121
2     150
3     150
4     130
5     166
6     150
7     168
8     147
9     125
10    164
dtype: int32

In [6]:
scores_pd['國文'] + scores_pd['英文'] + scores_pd['地理'] + scores_pd['歷史'] + scores_pd['數學']

學號
1     340
2     399
3     370
4     326
5     398
6     367
7     409
8     360
9     361
10    392
11    360
12    366
13    372
14    432
15    361
16    371
17    423
18    354
19    361
20    409
21    409
22    356
23    292
24    337
25    377
26    418
27    359
28    366
29    360
30    341
31    352
32    356
33    381
34    344
35    407
36    450
37    393
38    416
39    404
40    339
41    375
42    343
43    401
44    291
45    344
46    392
47    416
48    410
49    369
50    344
dtype: int32

In [7]:
#統計的實體方法,sum()
scores_pd['總分'] = scores_pd[['國文','英文','數學','地理','歷史']].sum(axis=1)
scores_pd
scores_pd['平均'] = scores_pd[['國文','英文','數學','地理','歷史']].mean(axis=1)
scores_pd

科目   國文   英文   數學   地理   歷史   總分    平均
學號
1    62   65   59  100   54  340  68.0
2    50   70  100   88   91  399  79.8
3    56   66   94   79   75  370  74.0
4    62   64   68   50   82  326  65.2
5    68   85   98   64   83  398  79.6
6    65   95   85   69   53  367  73.4
7    89  100   79   61   80  409  81.8
8    86   82   61   56   75  360  72.0
9    75   52   50   98   86  361  72.2
10   72   97   92   66   65  392  78.4
11   83   70   60   72   75  360  72.0
12   50   82   97   55   82  366  73.2
13   94   96   53   68   61  372  74.4
14   79   77  100   82   94  432  86.4
15   78   58   65   68   92  361  72.2
16   84   99   52   83   53  371  74.2
17   97   66   90   97   73  423  84.6
18   89   54   82   66   63  354  70.8
19   72   56   89   89   55  361  72.2
20  100   86   78   95   50  409  81.8
21   66   52   94   97  100  409  81.8
22   56   89   96   50   65  356  71.2
23   76   51   55   52   58  292  58.4
24   51   80   52   57   97  337  67.4
25   87   91   66   69   64  377  75.4
26   84   90   89   77   78  418  83.6
27   63   83   54   78   81  359  71.8
28   52   60   83   81   90  366  73.2
29   56   91   67   74   72  360  72.0
30   53   92   67   73   56  341  68.2
31   71   67   99   57   58  352  70.4
32   98   54   68   85   51  356  71.2
33   93   87   50   53   98  381  76.2
34   81   61   86   61   55  344  68.8
35   92  100   65   57   93  407  81.4
36   70   95   93   92  100  450  90.0
37   67   81   60   94   91  393  78.6
38   98  100   89   60   69  416  83.2
39   72  100   81   88   63  404  80.8
40   54   59   97   54   75  339  67.8
41   93   75   69   73   65  375  75.0
42   56   69   80   72   66  343  68.6
43   91   63   99   56   92  401  80.2
44   55   50   53   66   67  291  58.2
45   51   83   53   96   61  344  68.8
46   82   77   89   72   72  392  78.4
47   65   69  100  100   82  416  83.2
48   67   86   83   83   91  410  82.0
49   89   66   66   54   94  369  73.8
50   78   62   51   90   63  344  68.8

In [8]:
scores_pd['排名'] = scores_pd['總分'].rank(method='min',ascending=False)
scores_pd

科目   國文   英文   數學   地理   歷史   總分    平均    排名
學號
1    62   65   59  100   54  340  68.0  45.0
2    50   70  100   88   91  399  79.8  14.0
3    56   66   94   79   75  370  74.0  24.0
4    62   64   68   50   82  326  65.2  48.0
5    68   85   98   64   83  398  79.6  15.0
6    65   95   85   69   53  367  73.4  26.0
7    89  100   79   61   80  409  81.8   8.0
8    86   82   61   56   75  360  72.0  32.0
9    75   52   50   98   86  361  72.2  29.0
10   72   97   92   66   65  392  78.4  17.0
11   83   70   60   72   75  360  72.0  32.0
12   50   82   97   55   82  366  73.2  27.0
13   94   96   53   68   61  372  74.4  22.0
14   79   77  100   82   94  432  86.4   2.0
15   78   58   65   68   92  361  72.2  29.0
16   84   99   52   83   53  371  74.2  23.0
17   97   66   90   97   73  423  84.6   3.0
18   89   54   82   66   63  354  70.8  38.0
19   72   56   89   89   55  361  72.2  29.0
20  100   86   78   95   50  409  81.8   8.0
21   66   52   94   97  100  409  81.8   8.0
22   56   89   96   50   65  356  71.2  36.0
23   76   51   55   52   58  292  58.4  49.0
24   51   80   52   57   97  337  67.4  47.0
25   87   91   66   69   64  377  75.4  20.0
26   84   90   89   77   78  418  83.6   4.0
27   63   83   54   78   81  359  71.8  35.0
28   52   60   83   81   90  366  73.2  27.0
29   56   91   67   74   72  360  72.0  32.0
30   53   92   67   73   56  341  68.2  44.0
31   71   67   99   57   58  352  70.4  39.0
32   98   54   68   85   51  356  71.2  36.0
33   93   87   50   53   98  381  76.2  19.0
34   81   61   86   61   55  344  68.8  40.0
35   92  100   65   57   93  407  81.4  11.0
36   70   95   93   92  100  450  90.0   1.0
37   67   81   60   94   91  393  78.6  16.0
38   98  100   89   60   69  416  83.2   5.0
39   72  100   81   88   63  404  80.8  12.0
40   54   59   97   54   75  339  67.8  46.0
41   93   75   69   73   65  375  75.0  21.0
42   56   69   80   72   66  343  68.6  43.0
43   91   63   99   56   92  401  80.2  13.0
44   55   50   53   66   67  291  58.2  50.0
45   51   83   53   96   61  344  68.8  40.0
46   82   77   89   72   72  392  78.4  17.0
47   65   69  100  100   82  416  83.2   5.0
48   67   86   83   83   91  410  82.0   7.0
49   89   66   66   54   94  369  73.8  25.0
50   78   62   51   90   63  344  68.8  40.0

In [9]:
scores_pd.sort_values(by='排名')

科目   國文   英文   數學   地理   歷史   總分    平均    排名
學號
36   70   95   93   92  100  450  90.0   1.0
14   79   77  100   82   94  432  86.4   2.0
17   97   66   90   97   73  423  84.6   3.0
26   84   90   89   77   78  418  83.6   4.0
38   98  100   89   60   69  416  83.2   5.0
47   65   69  100  100   82  416  83.2   5.0
48   67   86   83   83   91  410  82.0   7.0
20  100   86   78   95   50  409  81.8   8.0
7    89  100   79   61   80  409  81.8   8.0
21   66   52   94   97  100  409  81.8   8.0
35   92  100   65   57   93  407  81.4  11.0
39   72  100   81   88   63  404  80.8  12.0
43   91   63   99   56   92  401  80.2  13.0
2    50   70  100   88   91  399  79.8  14.0
5    68   85   98   64   83  398  79.6  15.0
37   67   81   60   94   91  393  78.6  16.0
46   82   77   89   72   72  392  78.4  17.0
10   72   97   92   66   65  392  78.4  17.0
33   93   87   50   53   98  381  76.2  19.0
25   87   91   66   69   64  377  75.4  20.0
41   93   75   69   73   65  375  75.0  21.0
13   94   96   53   68   61  372  74.4  22.0
16   84   99   52   83   53  371  74.2  23.0
3    56   66   94   79   75  370  74.0  24.0
49   89   66   66   54   94  369  73.8  25.0
6    65   95   85   69   53  367  73.4  26.0
28   52   60   83   81   90  366  73.2  27.0
12   50   82   97   55   82  366  73.2  27.0
19   72   56   89   89   55  361  72.2  29.0
9    75   52   50   98   86  361  72.2  29.0
15   78   58   65   68   92  361  72.2  29.0
8    86   82   61   56   75  360  72.0  32.0
11   83   70   60   72   75  360  72.0  32.0
29   56   91   67   74   72  360  72.0  32.0
27   63   83   54   78   81  359  71.8  35.0
22   56   89   96   50   65  356  71.2  36.0
32   98   54   68   85   51  356  71.2  36.0
18   89   54   82   66   63  354  70.8  38.0
31   71   67   99   57   58  352  70.4  39.0
45   51   83   53   96   61  344  68.8  40.0
50   78   62   51   90   63  344  68.8  40.0
34   81   61   86   61   55  344  68.8  40.0
42   56   69   80   72   66  343  68.6  43.0
30   53   92   67   73   56  341  68.2  44.0
1    62   65   59  100   54  340  68.0  45.0
40   54   59   97   54   75  339  67.8  46.0
24   51   80   52   57   97  337  67.4  47.0
4    62   64   68   50   82  326  65.2  48.0
23   76   51   55   52   58  292  58.4  49.0
44   55   50   53   66   67  291  58.2  50.0

In [10]:
def format60(v:int):
    if v >= 60:
        return '及格'
    else:
        return '不及格'

scores_pd[['國文','英文','數學','地理','歷史']].style.format(format60)

In [11]:
scores_pd.style\
.highlight_between(left=0,
                   right=59,
                   color='pink',
                   subset=['國文','英文','數學','地理','歷史'],
                   props='color:white;background-color:pink')\
.format(precision=0,subset=['平均','排名']).to_excel('scores.xlsx')